fundo.caixa=br/caixa/sispl/theme/azul/fundo.jpg
button.type1=br/caixa/sispl/theme/azul/botao_released.png
button.type1.pressed=br/caixa/sispl/theme/azul/botao_pressed.png
button.type1.fontName=Arial
button.type1.fontColor=16777215
button.type1.fontSize=18
button.type2=br/caixa/sispl/theme/azul/botao_confirmar_released.png
button.type2.pressed=br/caixa/sispl/theme/azul/botao_confirmar_pressed.png
button.type2.fontName=Arial
button.type2.fontColor=16777215
button.type2.fontSize=12
button.type3=br/caixa/sispl/theme/azul/botao_confirmar_released.png
button.type3.pressed=br/caixa/sispl/theme/azul/botao_confirmar_pressed.png
button.type3.fontName=Arial
button.type3.fontColor=16744544
button.type3.fontSize=12
button.type4=br/caixa/sispl/theme/azul/botao_confirmar_released.png
button.type4.pressed=br/caixa/sispl/theme/azul/botao_confirmar_pressed.png
button.type4.fontName=Arial
button.type4.fontColor=65280
button.type4.fontSize=12
