import { useMemo, useState } from 'react'
import './App.css'

type Cafe = { id:number; nome:string; origem:string; notas:string; preco:number; torra:string; perfil:string; moagens:string[]; disponivel:boolean; arte:string }
type Item = Cafe & { quantidade:number; moagem:string }
const cafes:Cafe[]=[
 {id:1,nome:'Serra do Caparaó',origem:'Minas Gerais, Brasil',notas:'Cacau, rapadura e ameixa',preco:42,torra:'Média',perfil:'Achocolatado',moagens:['Em grãos','Coado','Espresso'],disponivel:true,arte:'ouro'},
 {id:2,nome:'Mata Atlântica',origem:'Espírito Santo, Brasil',notas:'Jasmim, mel e limão siciliano',preco:48,torra:'Clara',perfil:'Floral',moagens:['Em grãos','Coado'],disponivel:true,arte:'verde'},
 {id:3,nome:'Terra Vermelha',origem:'Cerrado Mineiro, Brasil',notas:'Morango, melaço e caramelo',preco:46,torra:'Clara',perfil:'Frutado',moagens:['Em grãos','Prensa francesa'],disponivel:true,arte:'terra'},
 {id:4,nome:'Noite de Pinhão',origem:'Mantiqueira, Brasil',notas:'Castanha, chocolate amargo e especiarias',preco:44,torra:'Escura',perfil:'Achocolatado',moagens:['Em grãos','Espresso'],disponivel:false,arte:'noite'}]
const dinheiro=(n:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n)
const Campo=({nome,valor,opcoes,mudar}:{nome:string;valor:string;opcoes:string[]; mudar:(v:string)=>void})=><label>{nome}<select value={valor} onChange={e=>mudar(e.target.value)}>{opcoes.map(x=><option key={x}>{x}</option>)}</select></label>
export default function App(){
 const [torra,setTorra]=useState('Todas'),[perfil,setPerfil]=useState('Todos'),[moagem,setMoagem]=useState('Todas'),[limite,setLimite]=useState(60),[carrinho,setCarrinho]=useState<Item[]>([]),[aberto,setAberto]=useState(false),[aviso,setAviso]=useState(false),[detalhe,setDetalhe]=useState<Cafe|null>(null)
 const filtrados=useMemo(()=>cafes.filter(c=>(torra==='Todas'||c.torra===torra)&&(perfil==='Todos'||c.perfil===perfil)&&(moagem==='Todas'||c.moagens.includes(moagem))&&c.preco<=limite),[torra,perfil,moagem,limite])
 const adicionar=(c:Cafe, moagemEscolhida=c.moagens[0], quantidade=1)=>{if(!c.disponivel)return;setCarrinho(a=>{const i=a.find(x=>x.id===c.id&&x.moagem===moagemEscolhida);return i?a.map(x=>x===i?{...x,quantidade:x.quantidade+quantidade}:x):[...a,{...c,moagem:moagemEscolhida,quantidade}]});setDetalhe(null);setAberto(true)}
 const limpar=()=>{setTorra('Todas');setPerfil('Todos');setMoagem('Todas');setLimite(60)};const total=carrinho.reduce((a,x)=>a+x.preco*x.quantidade,0)
 return <><a className="skip" href="#catalogo">Pular para o catálogo</a><header><a className="marca" href="#inicio">terra <i>&</i> torra</a><nav aria-label="Navegação principal"><a href="#catalogo">Cafés</a><a href="#origem">Origem</a></nav><button className="sacola" onClick={()=>setAberto(true)}>Sacola <b>{carrinho.reduce((a,x)=>a+x.quantidade,0)}</b></button></header><main>
 <section className="hero" id="inicio"><p className="selo">CAFÉ DE PEQUENOS PRODUTORES</p><h1>Tempo para sentir<br/><em>o que a terra diz.</em></h1><p>Microlotes brasileiros torrados com precisão e enviados no auge do aroma.</p><a className="botao" href="#catalogo">Conhecer cafés ↘</a><div className="xicara" role="img" aria-label="Ilustração de uma xícara de café">☕</div></section>
 <section className="atalhos"><p>Escolha pelo que desperta em você</p>{['Frutado','Achocolatado','Floral'].map(x=><button key={x} onClick={()=>{setPerfil(x);document.getElementById('catalogo')?.scrollIntoView()}}>{x}<span>↗</span></button>)}</section>
 <section className="catalogo" id="catalogo"><p className="selo">SELEÇÃO DA SEMANA</p><h2>Cafés que contam<br/>de onde vieram.</h2><div className="conteudo"><aside><h3>Filtrar seleção</h3><Campo nome="Torra" valor={torra} opcoes={['Todas','Clara','Média','Escura']} mudar={setTorra}/><Campo nome="Perfil" valor={perfil} opcoes={['Todos','Frutado','Achocolatado','Floral']} mudar={setPerfil}/><Campo nome="Moagem" valor={moagem} opcoes={['Todas','Em grãos','Coado','Espresso','Prensa francesa']} mudar={setMoagem}/><label>Até {dinheiro(limite)}<input aria-label="Faixa de preço máxima" type="range" min="35" max="60" value={limite} onChange={e=>setLimite(+e.target.value)}/></label><button className="limpar" onClick={limpar}>Limpar filtros</button></aside><div className="grade" aria-live="polite">{filtrados.length?filtrados.map(c=><article key={c.id}><button className={`arte ${c.arte}`} onClick={()=>setDetalhe(c)} aria-label={`Ver detalhes de ${c.nome}`}>☕</button><p>{c.origem}</p><h3>{c.nome}</h3><small>{c.notas}</small><div className="preco"><b>{dinheiro(c.preco)}</b>{c.disponivel?<button onClick={()=>adicionar(c)}>Adicionar</button>:<span>Indisponível</span>}</div></article>):<div className="vazio"><h3>Nenhum grão encontrou estes filtros.</h3><p>Experimente abrir a seleção novamente.</p><button className="botao" onClick={limpar}>Limpar filtros</button></div>}</div></div></section>
 <section className="origem" id="origem"><div><p className="selo">DA ORIGEM À SUA XÍCARA</p><h2>Relações longas.<br/><em>Torra recente.</em></h2></div><p>Visitamos cada produtor, escolhemos lotes com história e torramos em pequenas levas. Sem atalhos — apenas café que faz sentido no paladar.</p></section></main><footer><span>Terra & Torra © 2026</span><span>Uma experiência demonstrativa. Não realizamos pagamentos.</span></footer>
 {detalhe&&<Detalhe cafe={detalhe} fechar={()=>setDetalhe(null)} adicionar={adicionar}/>} {aberto&&<aside className="painel" aria-label="Carrinho demonstrativo"><div className="topo"><h2>Sua sacola</h2><button onClick={()=>setAberto(false)} aria-label="Fechar carrinho">×</button></div>{carrinho.length===0?<p className="vazio">Sua sacola ainda está vazia.</p>:<><ul>{carrinho.map(i=><li key={`${i.id}-${i.moagem}`}><div><b>{i.nome}</b><small>{i.moagem}</small><button onClick={()=>setCarrinho(a=>a.filter(x=>x!==i))}>Remover</button></div><div className="contador"><button aria-label={`Diminuir ${i.nome}`} onClick={()=>setCarrinho(a=>a.map(x=>x===i?{...x,quantidade:Math.max(1,x.quantidade-1)}:x))}>−</button><span>{i.quantidade}</span><button aria-label={`Aumentar ${i.nome}`} onClick={()=>setCarrinho(a=>a.map(x=>x===i?{...x,quantidade:x.quantidade+1}:x))}>+</button></div><b>{dinheiro(i.preco*i.quantidade)}</b></li>)}</ul><div className="total"><span>Subtotal</span><b>{dinheiro(total)}</b></div><button className="botao finalizar" onClick={()=>setAviso(true)}>Finalizar demonstração</button></>}</aside>}{aviso&&<div className="aviso" role="status"><p><b>É só uma demonstração.</b> Nenhum pagamento foi processado e nenhum dado pessoal foi coletado.</p><button onClick={()=>setAviso(false)} aria-label="Fechar aviso">×</button></div>}</>}
function Detalhe({cafe,fechar,adicionar}:{cafe:Cafe;fechar:()=>void;adicionar:(c:Cafe,m:string,q:number)=>void}){const [moagem,setMoagem]=useState(cafe.moagens[0]),[quantidade,setQuantidade]=useState(1);return <div className="fundo"><section className="detalhe" role="dialog" aria-modal="true" aria-labelledby="titulo-detalhe"><button className="fechar" onClick={fechar} aria-label="Fechar detalhe">×</button><div className={`arte grande ${cafe.arte}`}>☕</div><p className="selo">{cafe.origem}</p><h2 id="titulo-detalhe">{cafe.nome}</h2><p>{cafe.notas}</p><b>{dinheiro(cafe.preco)}</b>{cafe.disponivel?<><Campo nome="Moagem escolhida" valor={moagem} opcoes={cafe.moagens} mudar={setMoagem}/><div className="acoes"><div className="contador"><button onClick={()=>setQuantidade(Math.max(1,quantidade-1))}>−</button><span>{quantidade}</span><button onClick={()=>setQuantidade(quantidade+1)}>+</button></div><button className="botao" onClick={()=>adicionar(cafe,moagem,quantidade)}>Adicionar à sacola</button></div></>:<p className="indisponivel">Este lote está indisponível no momento.</p>}</section></div>}
